# Resolve relative to the Flutter runner, not plugin junctions (Windows REALPATH
# does not consistently resolve Flutter's directory junctions).
get_filename_component(MIMIR_NATIVE_ROOT "${CMAKE_SOURCE_DIR}/../.." ABSOLUTE)
set(MIMIR_DYNAMIC_BACKENDS ON CACHE BOOL "" FORCE)
set(MIMIR_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GGML_METAL OFF CACHE BOOL "" FORCE)
set(GGML_BLAS OFF CACHE BOOL "" FORCE)
set(GGML_OPENMP OFF CACHE BOOL "" FORCE)
set(LLAMA_CURL OFF CACHE BOOL "" FORCE)
# Both optional GPU backends are opt-in at build time, independent at runtime.
set(GGML_CUDA OFF CACHE BOOL "" FORCE)
set(GGML_VULKAN OFF CACHE BOOL "" FORCE)
foreach(backend IN ITEMS CUDA VULKAN)
    if("$ENV{MIMIR_BACKENDS}" MATCHES "(^|;)${backend}(;|$)")
        set(GGML_${backend} ON CACHE BOOL "" FORCE)
    endif()
endforeach()
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$" OR CMAKE_GENERATOR_PLATFORM STREQUAL "x64")
    set(GGML_CPU_ALL_VARIANTS ON CACHE BOOL "" FORCE)
endif()
# All transitive libraries live beside each other in the installed lib directory.
if(UNIX)
    set(CMAKE_BUILD_RPATH_USE_ORIGIN ON)
    set(CMAKE_INSTALL_RPATH "$ORIGIN")
    set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
endif()
if(GGML_CUDA)
    find_package(CUDAToolkit REQUIRED)
endif()
add_subdirectory("${MIMIR_NATIVE_ROOT}/runtime" "${CMAKE_CURRENT_BINARY_DIR}/runtime")
function(mimir_collect_libraries directory output)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    set(libraries)
    foreach(target IN LISTS targets)
        get_target_property(kind ${target} TYPE)
        if(kind STREQUAL "SHARED_LIBRARY" OR kind STREQUAL "MODULE_LIBRARY")
            list(APPEND libraries "$<TARGET_FILE:${target}>")
            if(UNIX AND kind STREQUAL "SHARED_LIBRARY")
                list(APPEND libraries "$<TARGET_SONAME_FILE:${target}>")
            endif()
        endif()
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        mimir_collect_libraries("${child}" nested)
        list(APPEND libraries ${nested})
    endforeach()
    set(${output} "${libraries}" PARENT_SCOPE)
endfunction()
mimir_collect_libraries("${MIMIR_NATIVE_ROOT}/runtime" libraries)
# Supply the release CRT with portable Windows bundles; don't install outside the bundle.
if(MSVC)
    set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP TRUE)
    include(InstallRequiredSystemLibraries)
    list(APPEND libraries ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS})
endif()
# CUDA user-space runtime dependencies are redistributable separately from the
# system driver. Include them in GPU packages; never copy libcuda/nvcuda drivers.
if(GGML_CUDA)
    if(WIN32)
        file(GLOB cuda_runtime_libraries "${CUDAToolkit_BIN_DIR}/cudart64*.dll"
            "${CUDAToolkit_BIN_DIR}/cublas64*.dll" "${CUDAToolkit_BIN_DIR}/cublasLt64*.dll")
    else()
        file(GLOB cuda_runtime_libraries "${CUDAToolkit_LIBRARY_DIR}/libcudart.so*"
            "${CUDAToolkit_LIBRARY_DIR}/libcublas.so*" "${CUDAToolkit_LIBRARY_DIR}/libcublasLt.so*")
    endif()
    if(NOT cuda_runtime_libraries)
        message(FATAL_ERROR "CUDA runtime redistributables not found; cannot create a standalone GPU package")
    endif()
    list(APPEND libraries ${cuda_runtime_libraries})
endif()
set(mimir_native_bundled_libraries "${libraries}" PARENT_SCOPE)
