# Backbone config; HRM half_layers splits this into 24 L and 24 H layers.
n_layers: 48

hidden_size: 4096
num_heads: 32  # head size 128
expansion: 4

norm_type: pre
norm_eps: 1e-6

rope_theta: 10000.0
pos_emb_type: rope

init_type: lecun_normal
