sets:
  hrm_danish_ifeval_da_shard_0:
    description: "IFEval DA shard 0/8."
    tasks:
      - name: dfm_evals/ifeval-da
        args: [-T, num_shards=8, -T, shard_index=0]
    args: &ifeval_args
      - --model
      - "{{target_model}}"
      - --sample-shuffle
      - "4242"
      - --temperature
      - "0"

  hrm_danish_ifeval_da_shard_1:
    description: "IFEval DA shard 1/8."
    tasks:
      - name: dfm_evals/ifeval-da
        args: [-T, num_shards=8, -T, shard_index=1]
    args: *ifeval_args

  hrm_danish_ifeval_da_shard_2:
    description: "IFEval DA shard 2/8."
    tasks:
      - name: dfm_evals/ifeval-da
        args: [-T, num_shards=8, -T, shard_index=2]
    args: *ifeval_args

  hrm_danish_ifeval_da_shard_3:
    description: "IFEval DA shard 3/8."
    tasks:
      - name: dfm_evals/ifeval-da
        args: [-T, num_shards=8, -T, shard_index=3]
    args: *ifeval_args

  hrm_danish_ifeval_da_shard_4:
    description: "IFEval DA shard 4/8."
    tasks:
      - name: dfm_evals/ifeval-da
        args: [-T, num_shards=8, -T, shard_index=4]
    args: *ifeval_args

  hrm_danish_ifeval_da_shard_5:
    description: "IFEval DA shard 5/8."
    tasks:
      - name: dfm_evals/ifeval-da
        args: [-T, num_shards=8, -T, shard_index=5]
    args: *ifeval_args

  hrm_danish_ifeval_da_shard_6:
    description: "IFEval DA shard 6/8."
    tasks:
      - name: dfm_evals/ifeval-da
        args: [-T, num_shards=8, -T, shard_index=6]
    args: *ifeval_args

  hrm_danish_ifeval_da_shard_7:
    description: "IFEval DA shard 7/8."
    tasks:
      - name: dfm_evals/ifeval-da
        args: [-T, num_shards=8, -T, shard_index=7]
    args: *ifeval_args
