"""Generate letter-category exceptions to llama.cpp's simple case-mapping flags."""
import argparse
from pathlib import Path
import re
import regex

__all__ = []


def _main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    source = args.source.read_text()
    mappings = []
    for name in ['uppercase', 'lowercase']:
        body = source.split('unicode_map_' + name + ' = {')[1].split('};')[0]
        mappings.append({int(dst, 16) for _, dst in re.findall(r'\{(0x[\dA-Fa-f]+),\s*(0x[\dA-Fa-f]+)\}', body)})
    text = ''.join(map(chr, range(0x110000)))
    exceptions = {}
    for category, tag in [('Lu', 1), ('Lt', 1), ('Ll', 2)]:
        for match in regex.finditer(fr'\p{{{category}}}+', text):
            for codepoint in range(match.start(), match.end()):
                actual = 1 if codepoint in mappings[0] else 2 if codepoint in mappings[1] else 0
                if actual != tag:
                    exceptions[codepoint] = tag
    ranges = []
    for codepoint, tag in sorted(exceptions.items()):
        if ranges and ranges[-1][1] + 1 == codepoint and ranges[-1][2] == tag:
            ranges[-1][1] = codepoint
        else:
            ranges.append([codepoint, codepoint, tag])
    lines = ['// Generated by native/mimir/tests/generate_letter_cases.py using regex ' + regex.__version__ + '.',
             '// 1 = Unicode Lu/Lt, 2 = Ll; only exceptions to simple case-mapping flags.',
             'static const struct { uint32_t first; uint32_t last; uint8_t kind; } unicode_letter_case_exceptions[] = {']
    lines += [f'    {{0x{first:x}, 0x{last:x}, {tag}}},' for first, last, tag in ranges]
    lines += ['};', '']
    args.output.write_text('\n'.join(lines))
    print(len(ranges), 'case ranges')


if __name__ == '__main__':
    _main()
