#!/usr/bin/env python3
"""Build and validate the DFM11 Folketing error-correction replacement.

The DFM10 source was generated by applying a small, deterministic set of OCR
confusions to a clean target.  This builder admits only rows whose complete
source/target relationship can be explained by that generator and whose target
passes conservative text-quality checks.  It never mutates the DFM10 package.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import heapq
import http.client
import json
import os
import re
import shutil
import time
import unicodedata
import urllib.error
import urllib.request
from collections import Counter
from concurrent.futures import FIRST_COMPLETED, ProcessPoolExecutor, ThreadPoolExecutor, wait
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "data/dfm11_source_cache/dfm10-folketingets-dokumenter-error-correction"
DEFAULT_OUTPUT = ROOT / "exports_dfm11/dfm11-folketingets-dokumenter-error-correction-repaired"
DEFAULT_AUDITED_OUTPUT = ROOT / "exports_dfm11/dfm11-folketingets-dokumenter-error-correction"
DEFAULT_SAMPLE = ROOT / "data/dfm11_folketing_error_correction/audit_sample/folketingets-dokumenter-error-correction"
PROMPT_PREFIX = "Ret OCR- og tekstfejlene.\n\n"
SOURCE_REVISION = "741da1387a126900ec96e13fb065d5cd7f9f89b6"
CONFUSIONS = {
    "m": "rn",
    "M": "rn",
    "l": "1",
    "L": "1",
    "I": "l",
    "o": "0",
    "O": "0",
    "e": "c",
    "E": "c",
}
CONTROL_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
WORD_RE = re.compile(r"\w+", re.UNICODE)
DOT_LEADER_RE = re.compile(r"(?:\.{5,}|(?:\.\s*){6,})")
FINAL_PACKAGE_NAME = "dfm11-folketingets-dokumenter-error-correction"
FINAL_HF_ID = f"schneiderkamplab/{FINAL_PACKAGE_NAME}"
AUDIT_JSON_SCHEMA = {
    "type": "object",
    "properties": {
        "keep": {"type": "boolean"},
        "coherent_danish": {"type": "boolean"},
        "residual_ocr_quality_ok": {"type": "boolean"},
        "complete_non_list_text": {"type": "boolean"},
        "useful_training_example": {"type": "boolean"},
        "primary_failure_type": {
            "type": "string",
            "enum": [
                "none",
                "residual_ocr",
                "fragment_or_list",
                "wrong_language",
                "low_value",
                "other",
            ],
        },
        "complaint": {"type": "string"},
    },
    "required": [
        "keep",
        "coherent_danish",
        "residual_ocr_quality_ok",
        "complete_non_list_text",
        "useful_training_example",
        "primary_failure_type",
        "complaint",
    ],
    "additionalProperties": False,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    build = subparsers.add_parser("build", help="filter all source shards")
    build.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    build.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    build.add_argument("--workers", type=int, default=13)
    build.add_argument("--force", action="store_true")

    sample = subparsers.add_parser("sample", help="make a deterministic audit sample")
    sample.add_argument("--input", type=Path, default=DEFAULT_OUTPUT)
    sample.add_argument("--output", type=Path, default=DEFAULT_SAMPLE)
    sample.add_argument("--rows", type=int, default=5000)
    sample.add_argument("--seed", type=int, default=110043)
    sample.add_argument("--force", action="store_true")

    audit = subparsers.add_parser("audit", help="task-aware audit of one sample partition")
    audit.add_argument("--input", type=Path, default=DEFAULT_SAMPLE)
    audit.add_argument("--output", type=Path, required=True)
    audit.add_argument("--base-url", required=True)
    audit.add_argument("--model", required=True)
    audit.add_argument("--partitions", type=int, default=1)
    audit.add_argument("--partition-index", type=int, default=0)
    audit.add_argument("--concurrency", type=int, default=64)
    audit.add_argument("--retries", type=int, default=4)
    audit.add_argument("--timeout", type=int, default=300)
    audit.add_argument("--force", action="store_true")
    audit.add_argument("--resume", action="store_true")

    sidecar = subparsers.add_parser(
        "sidecar-unresolved",
        help="preserve and fail-closed exclude rows unresolved after judge retries",
    )
    sidecar.add_argument("--input", type=Path, default=DEFAULT_OUTPUT)
    sidecar.add_argument("--audit", type=Path, action="append", required=True)
    sidecar.add_argument("--sidecar", type=Path, required=True)
    sidecar.add_argument("--expected-rows", type=int, required=True)
    sidecar.add_argument("--expected-unresolved", type=int, required=True)
    sidecar.add_argument("--judge-model", required=True)

    finalize = subparsers.add_parser("finalize", help="remove full-audit rejections")
    finalize.add_argument("--input", type=Path, default=DEFAULT_OUTPUT)
    finalize.add_argument("--output", type=Path, default=DEFAULT_AUDITED_OUTPUT)
    finalize.add_argument("--audit", type=Path, action="append", required=True)
    finalize.add_argument("--expected-rows", type=int, required=True)
    finalize.add_argument("--workers", type=int, default=13)
    finalize.add_argument("--force", action="store_true")

    record_upload = subparsers.add_parser("record-upload", help="verify and pin a completed Hub upload")
    record_upload.add_argument("--package", type=Path, default=DEFAULT_AUDITED_OUTPUT)
    record_upload.add_argument("--repo-id", default=FINAL_HF_ID)
    record_upload.add_argument("--token-env", default="HF_TOKEN")
    record_upload.add_argument(
        "--config",
        type=Path,
        default=ROOT / "config/data/dfm11_tool_replacements.yaml",
    )
    record_upload.add_argument(
        "--receipt",
        type=Path,
        default=ROOT / "logs/dfm11_folketing_error_correction/upload_receipt.json",
    )

    gate = subparsers.add_parser("gate", help="validate merged audit decisions")
    gate.add_argument("--audit", type=Path, action="append", required=True)
    gate.add_argument("--expected-rows", type=int, default=5000)
    gate.add_argument("--minimum-keep-rate", type=float, default=0.90)
    gate.add_argument(
        "--output",
        type=Path,
        default=ROOT / "logs/dfm11_folketing_error_correction/production_gate.json",
    )
    return parser.parse_args()


def corruption_edit_count(source: str, target: str) -> int | None:
    """Return the minimum declared OCR edits mapping target to source."""
    states: dict[int, int] = {0: 0}
    for char in target:
        next_states: dict[int, int] = {}
        replacement = CONFUSIONS.get(char)
        for source_index, edits in states.items():
            if source.startswith(char, source_index):
                end = source_index + len(char)
                next_states[end] = min(next_states.get(end, edits), edits)
            if replacement and source.startswith(replacement, source_index):
                end = source_index + len(replacement)
                changed = edits + 1
                next_states[end] = min(next_states.get(end, changed), changed)
        if not next_states:
            return None
        states = next_states
    return states.get(len(source))


def target_quality_failure(text: str) -> str | None:
    if len(text) < 100 or len(WORD_RE.findall(text)) < 20:
        return "target_too_short"
    if CONTROL_RE.search(text) or "\ufffd" in text:
        return "target_control_or_replacement_character"
    alnum = sum(char.isalnum() for char in text)
    if alnum / max(1, len(text)) < 0.18:
        return "target_low_alphanumeric_density"

    letters = [char for char in text if char.isalpha()]
    non_latin = sum("LATIN" not in unicodedata.name(char, "") for char in letters)
    if non_latin / max(1, len(letters)) > 0.002:
        return "target_non_latin_ocr_artifacts"

    lines = [line.strip() for line in text.splitlines() if line.strip()]
    fragment_lines = sum(sum(char.isalnum() for char in line) <= 2 for line in lines)
    if len(lines) >= 8 and fragment_lines / len(lines) >= 0.25:
        return "target_fragmented_lines"
    if len(DOT_LEADER_RE.findall(text)) >= 4:
        return "target_index_or_dot_leaders"
    return None


def validate_row(row: dict[str, Any]) -> tuple[str | None, int | None]:
    messages = row.get("messages")
    if not isinstance(messages, list) or len(messages) != 2:
        return "invalid_message_shape", None
    user, assistant = messages
    if user.get("role") != "user" or assistant.get("role") != "assistant":
        return "invalid_message_roles", None
    prompt = user.get("content")
    target = assistant.get("content")
    if not isinstance(prompt, str) or not isinstance(target, str):
        return "non_string_content", None
    if not prompt.startswith(PROMPT_PREFIX):
        return "unexpected_prompt", None

    source = prompt[len(PROMPT_PREFIX) :]
    failure = target_quality_failure(target)
    if failure:
        return failure, None
    edits = corruption_edit_count(source, target)
    if edits is None:
        return "source_target_not_declared_corruption", None
    if edits == 0:
        return "normalized_noop", edits
    if edits > 8:
        return "too_many_corruptions", edits
    return None, edits


def atomic_write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp.{os.getpid()}")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


def filter_shard(source: Path, destination: Path) -> dict[str, Any]:
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.tmp.{os.getpid()}")
    counts: Counter[str] = Counter()
    digest = hashlib.sha256()
    try:
        with gzip.open(source, "rt", encoding="utf-8") as reader, gzip.open(
            temporary, "wt", encoding="utf-8", compresslevel=6
        ) as writer:
            for line_number, line in enumerate(reader, start=1):
                counts["rows_seen"] += 1
                try:
                    row = json.loads(line)
                except json.JSONDecodeError:
                    counts["reject:invalid_json"] += 1
                    continue
                failure, edits = validate_row(row)
                if failure:
                    counts[f"reject:{failure}"] += 1
                    continue
                row.setdefault("metadata", {})["dfm11_repair"] = {
                    "name": "folketing_error_correction_contract_v1",
                    "declared_ocr_edits": edits,
                    "source_revision": SOURCE_REVISION,
                }
                encoded = (json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n").encode()
                writer.write(encoded.decode())
                digest.update(encoded)
                counts["rows_kept"] += 1
                counts[f"kept_edits:{edits}"] += 1
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)
    return {
        "source": str(source),
        "output": str(destination),
        "sha256_uncompressed": digest.hexdigest(),
        "counts": dict(counts),
    }


def build(args: argparse.Namespace) -> None:
    sources = sorted((args.input / "data").glob("train-*.jsonl.gz"))
    if not sources:
        raise FileNotFoundError(args.input / "data")
    if args.output.exists():
        if not args.force:
            raise FileExistsError(args.output)
        shutil.rmtree(args.output)
    (args.output / "data").mkdir(parents=True)
    work = [(source, args.output / "data" / source.name) for source in sources]
    with ProcessPoolExecutor(max_workers=min(args.workers, len(work))) as pool:
        results = list(pool.map(filter_shard, *(zip(*work))))

    totals: Counter[str] = Counter()
    for result in results:
        totals.update(result["counts"])
    manifest = {
        "name": args.output.name,
        "source_repo": "schneiderkamplab/dfm10-folketingets-dokumenter-error-correction",
        "source_revision": SOURCE_REVISION,
        "license": "cc-by-4.0",
        "filter_contract": "folketing_error_correction_contract_v1",
        "counts": dict(totals),
        "shards": results,
        "admission_status": "deterministically_filtered_pending_5000_row_audit",
    }
    atomic_write_json(args.output / "metadata" / "manifest.json", manifest)
    print(json.dumps(manifest["counts"], indent=2, sort_keys=True))


def sample(args: argparse.Namespace) -> None:
    sources = sorted((args.input / "data").glob("*.jsonl.gz"))
    if not sources:
        raise FileNotFoundError(args.input / "data")
    if args.output.exists():
        if not args.force:
            raise FileExistsError(args.output)
        shutil.rmtree(args.output)
    heap: list[tuple[int, int, dict[str, Any]]] = []
    ordinal = 0
    for source in sources:
        with gzip.open(source, "rt", encoding="utf-8") as handle:
            for line in handle:
                row = json.loads(line)
                source_id = str(row.get("metadata", {}).get("source_id") or ordinal)
                value = int.from_bytes(
                    hashlib.blake2b(f"{args.seed}\0{source_id}".encode(), digest_size=8).digest(),
                    "big",
                )
                item = (-value, ordinal, row)
                if len(heap) < args.rows:
                    heapq.heappush(heap, item)
                elif value < -heap[0][0]:
                    heapq.heapreplace(heap, item)
                ordinal += 1
    if len(heap) != args.rows:
        raise ValueError(f"requested {args.rows} rows, found {len(heap)}")
    selected = [item[2] for item in sorted(heap, key=lambda item: -item[0])]
    data = args.output / "data" / "sample.jsonl.gz"
    data.parent.mkdir(parents=True, exist_ok=True)
    temporary = data.with_name(f".{data.name}.tmp.{os.getpid()}")
    with gzip.open(temporary, "wt", encoding="utf-8", compresslevel=6) as handle:
        for row in selected:
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
    os.replace(temporary, data)
    atomic_write_json(
        args.output / "metadata" / "manifest.json",
        {"rows": len(selected), "seed": args.seed, "source": str(args.input)},
    )
    print(json.dumps({"output": str(args.output), "rows": len(selected), "population": ordinal}))


def audit_messages(row: dict[str, Any]) -> list[dict[str, str]]:
    messages = row["messages"]
    source = messages[0]["content"][len(PROMPT_PREFIX) :]
    target = messages[1]["content"]
    edits = row["metadata"]["dfm11_repair"]["declared_ocr_edits"]
    system = (
        "Du er en streng, opgavespecifik kvalitetskontrollør af dansk SFT-data. "
        "En deterministisk validator har allerede bevist, at inputtet blev dannet "
        "fra målet med præcis det oplyste antal syntetiske OCR-tegnfejl, og at målet "
        "retter dem alle uden andre ændringer. En forskel på kun 1-8 tegn er tilsigtet "
        "og må aldrig i sig selv føre til afvisning. Bedøm kun om målteksten er "
        "sammenhængende og nyttig dansk tekst uden alvorlige tilbageværende OCR-fejl, "
        "ufuldstændige fragmenter, registre/indholdsfortegnelser eller forkert sprog. "
        "Historisk dansk stavning og parlamentarisk sprog er gyldigt. Returnér kun JSON."
    )
    payload = {
        "synthetic_ocr_edits_proven_corrected": edits,
        "corrupted_input": source,
        "clean_target": target,
        "required_schema": {
            "keep": "boolean",
            "coherent_danish": "boolean",
            "residual_ocr_quality_ok": "boolean",
            "complete_non_list_text": "boolean",
            "useful_training_example": "boolean",
            "primary_failure_type": "none|residual_ocr|fragment_or_list|wrong_language|low_value|other",
            "complaint": "short string; none when keep=true",
        },
    }
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
    ]


def call_audit(args: argparse.Namespace, row: dict[str, Any], row_id: str) -> dict[str, Any]:
    body = {
        "model": args.model,
        "messages": audit_messages(row),
        "temperature": 0,
        "top_p": 1,
        # A small number of difficult rows consume substantial hidden reasoning
        # before emitting the constrained JSON object.
        "max_tokens": 2048,
        "response_format": {
            "type": "json_schema",
            "json_schema": {
                "name": "folketing_error_correction_audit",
                "schema": AUDIT_JSON_SCHEMA,
                "strict": True,
            },
        },
    }
    last_error = ""
    for attempt in range(args.retries + 1):
        try:
            request = urllib.request.Request(
                args.base_url.rstrip("/") + "/chat/completions",
                data=json.dumps(body).encode(),
                headers={"Content-Type": "application/json", "Authorization": "Bearer dummy"},
                method="POST",
            )
            with urllib.request.urlopen(request, timeout=args.timeout) as response:
                payload = json.loads(response.read().decode())
            content = payload["choices"][0]["message"]["content"]
            match = re.search(r"\{.*\}", content, re.S)
            if match is None:
                raise ValueError("judge returned no JSON object")
            verdict = json.loads(match.group(0))
            required = (
                "coherent_danish",
                "residual_ocr_quality_ok",
                "complete_non_list_text",
                "useful_training_example",
            )
            keep = bool(verdict.get("keep")) and all(bool(verdict.get(key)) for key in required)
            return {
                "row_id": row_id,
                "keep": keep,
                "primary_failure_type": str(verdict.get("primary_failure_type") or ("none" if keep else "other")),
                "complaint": str(verdict.get("complaint") or ("none" if keep else "judge_rejected")),
                "judge": verdict,
                "judge_model": args.model,
            }
        except (
            urllib.error.URLError,
            http.client.HTTPException,
            ConnectionError,
            TimeoutError,
            KeyError,
            ValueError,
            json.JSONDecodeError,
        ) as exc:
            last_error = f"{type(exc).__name__}: {exc}"
            if attempt < args.retries:
                time.sleep(min(10, 2**attempt))
    return {
        "row_id": row_id,
        "keep": False,
        "primary_failure_type": "judge_error",
        "complaint": "judge_error",
        "error": last_error,
        "judge_model": args.model,
    }


def audit(args: argparse.Namespace) -> None:
    if not 0 <= args.partition_index < args.partitions:
        raise ValueError("partition index is outside partition count")
    if args.force and args.resume:
        raise ValueError("--force and --resume are mutually exclusive")
    source_files = sorted((args.input / "data").glob("*.jsonl.gz"))
    if not source_files:
        raise FileNotFoundError(args.input / "data")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    partial = args.output.with_suffix(args.output.suffix + ".partial")
    if args.force:
        args.output.unlink(missing_ok=True)
        partial.unlink(missing_ok=True)
    elif args.output.exists():
        if not args.resume:
            raise FileExistsError(args.output)
        output_has_errors = False
        with args.output.open(encoding="utf-8") as handle:
            for line in handle:
                if line.strip() and "error" in json.loads(line):
                    output_has_errors = True
                    break
        if not output_has_errors:
            print(json.dumps({"partition": args.partition_index, "status": "already_complete", "output": str(args.output)}))
            return
        os.replace(args.output, partial)
    elif partial.exists() and not args.resume:
        raise FileExistsError(f"partial audit exists; use --resume or --force: {partial}")

    completed_ids: set[str] = set()
    counts: Counter[str] = Counter()
    if partial.exists():
        cleaned_partial = partial.with_name(f".{partial.name}.clean.{os.getpid()}")
        with partial.open(encoding="utf-8") as handle, cleaned_partial.open("w", encoding="utf-8") as cleaned:
            for line in handle:
                if not line.strip():
                    continue
                verdict = json.loads(line)
                if "error" in verdict:
                    counts["retrying_error_rows"] += 1
                    continue
                row_id = str(verdict["row_id"])
                if row_id in completed_ids:
                    raise ValueError(f"duplicate partial audit decision: {row_id}")
                completed_ids.add(row_id)
                cleaned.write(line)
                counts["resumed_rows"] += 1
            cleaned.flush()
            os.fsync(cleaned.fileno())
        os.replace(cleaned_partial, partial)

    def selected_rows():
        for source in source_files:
            with gzip.open(source, "rt", encoding="utf-8") as handle:
                for line_number, line in enumerate(handle):
                    row_id = f"{source.name}:{line_number}"
                    partition = int.from_bytes(
                        hashlib.blake2b(row_id.encode(), digest_size=8).digest(), "big"
                    ) % args.partitions
                    if partition != args.partition_index:
                        continue
                    counts["selected_rows"] += 1
                    if row_id in completed_ids:
                        continue
                    yield json.loads(line), row_id

    try:
        mode = "a" if partial.exists() else "w"
        with partial.open(mode, encoding="utf-8") as output, ThreadPoolExecutor(max_workers=args.concurrency) as pool:
            iterator = iter(selected_rows())
            pending: dict[Any, None] = {}
            while True:
                while len(pending) < args.concurrency:
                    try:
                        row, row_id = next(iterator)
                    except StopIteration:
                        break
                    pending[pool.submit(call_audit, args, row, row_id)] = None
                if not pending:
                    break
                completed, _ = wait(pending, return_when=FIRST_COMPLETED)
                for future in completed:
                    pending.pop(future)
                    verdict = future.result()
                    output.write(json.dumps(verdict, ensure_ascii=False, separators=(",", ":")) + "\n")
                    output.flush()
                    counts["rows"] += 1
                    counts["keep" if verdict["keep"] else "drop"] += 1
                    if "error" in verdict:
                        counts["judge_errors"] += 1
                    if counts["rows"] % 100 == 0:
                        output.flush()
                        os.fsync(output.fileno())
                        print(
                            f"partition={args.partition_index} new={counts['rows']} "
                            f"resumed={counts['resumed_rows']} selected={counts['selected_rows']}",
                            flush=True,
                        )
            output.flush()
            os.fsync(output.fileno())
        if counts["judge_errors"]:
            raise RuntimeError(
                f"partition {args.partition_index} has {counts['judge_errors']} unresolved judge errors; resume to retry"
            )
        os.replace(partial, args.output)
    except BaseException:
        raise
    print(json.dumps({"partition": args.partition_index, **counts}, sort_keys=True))


def sidecar_unresolved(args: argparse.Namespace) -> None:
    """Preserve repeatedly unresolved rows and exclude them fail-closed."""
    partitions = len(args.audit)
    completed_by_partition: list[set[str]] = []
    decision_paths: list[tuple[Path, Path]] = []
    decision_count = 0
    for output in args.audit:
        partial = output.with_suffix(output.suffix + ".partial")
        source = output if output.exists() else partial
        if not source.exists():
            raise FileNotFoundError(source)
        completed: set[str] = set()
        with source.open(encoding="utf-8") as handle:
            for line in handle:
                if not line.strip():
                    continue
                verdict = json.loads(line)
                if "error" in verdict:
                    raise ValueError(f"unresolved error verdict remains in {source}")
                row_id = str(verdict["row_id"])
                if row_id in completed:
                    raise ValueError(f"duplicate decision in {source}: {row_id}")
                completed.add(row_id)
        completed_by_partition.append(completed)
        decision_paths.append((source, output))
        decision_count += len(completed)

    unresolved: list[tuple[int, str, dict[str, Any]]] = []
    source_rows = 0
    for source in sorted((args.input / "data").glob("*.jsonl.gz")):
        with gzip.open(source, "rt", encoding="utf-8") as handle:
            for line_number, line in enumerate(handle):
                source_rows += 1
                row_id = f"{source.name}:{line_number}"
                partition = int.from_bytes(
                    hashlib.blake2b(row_id.encode(), digest_size=8).digest(), "big"
                ) % partitions
                if row_id not in completed_by_partition[partition]:
                    unresolved.append((partition, row_id, json.loads(line)))

    if source_rows != args.expected_rows:
        raise ValueError(f"source coverage {source_rows} != {args.expected_rows}")
    if decision_count + len(unresolved) != args.expected_rows:
        raise ValueError(
            f"decision coverage {decision_count} + {len(unresolved)} unresolved "
            f"!= {args.expected_rows}"
        )
    if len(unresolved) != args.expected_unresolved:
        raise ValueError(
            f"found {len(unresolved)} unresolved rows, expected {args.expected_unresolved}"
        )

    args.sidecar.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.sidecar.with_name(f".{args.sidecar.name}.tmp.{os.getpid()}")
    with temporary.open("w", encoding="utf-8") as handle:
        for partition, row_id, row in unresolved:
            handle.write(
                json.dumps(
                    {
                        "row_id": row_id,
                        "partition": partition,
                        "resolution": "fail_closed_exclusion_after_repeated_no_json",
                        "row": row,
                    },
                    ensure_ascii=False,
                    separators=(",", ":"),
                )
                + "\n"
            )
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, args.sidecar)

    unresolved_by_partition: dict[int, list[str]] = {}
    for partition, row_id, _ in unresolved:
        unresolved_by_partition.setdefault(partition, []).append(row_id)
    for partition, (source, output) in enumerate(decision_paths):
        additions = unresolved_by_partition.get(partition, [])
        if source == output:
            if additions:
                raise ValueError(f"complete partition {partition} has missing rows")
            continue
        with source.open("a", encoding="utf-8") as handle:
            for row_id in additions:
                handle.write(
                    json.dumps(
                        {
                            "row_id": row_id,
                            "keep": False,
                            "primary_failure_type": "unresolved_judge",
                            "complaint": "excluded after repeated schema-generation failure; preserved in sidecar",
                            "judge_model": args.judge_model,
                            "resolution": "fail_closed_exclusion",
                        },
                        ensure_ascii=False,
                        separators=(",", ":"),
                    )
                    + "\n"
                )
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(source, output)

    print(
        json.dumps(
            {
                "source_rows": source_rows,
                "existing_decisions": decision_count,
                "sidecar_unresolved": len(unresolved),
                "sidecar": str(args.sidecar),
                "resolution": "fail_closed_exclusion",
            },
            indent=2,
            sort_keys=True,
        )
    )


def _filter_audited_shard(work: tuple[Path, Path, set[int]]) -> dict[str, Any]:
    source, destination, rejected_lines = work
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.tmp.{os.getpid()}")
    seen = kept = rejected = 0
    try:
        with gzip.open(source, "rt", encoding="utf-8") as reader, gzip.open(
            temporary, "wt", encoding="utf-8", compresslevel=6
        ) as writer:
            for line_number, line in enumerate(reader):
                seen += 1
                if line_number in rejected_lines:
                    rejected += 1
                    continue
                writer.write(line)
                kept += 1
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)
    return {
        "file": f"data/{destination.name}",
        "seen": seen,
        "kept": kept,
        "rejected": rejected,
        "bytes": destination.stat().st_size,
        "sha256": hashlib.sha256(destination.read_bytes()).hexdigest(),
    }


FINAL_VALIDATOR = '''#!/usr/bin/env python3
import gzip, hashlib, json
from pathlib import Path

root = Path(__file__).parent
manifest = json.loads((root / "metadata/manifest.json").read_text())
rows = 0
for item in manifest["data_files"]:
    path = root / item["file"]
    if hashlib.sha256(path.read_bytes()).hexdigest() != item["sha256"]:
        raise ValueError(f"checksum mismatch: {path}")
    shard_rows = 0
    with gzip.open(path, "rt", encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            messages = row.get("messages")
            repair = row.get("metadata", {}).get("dfm11_repair", {})
            if not isinstance(messages, list) or len(messages) != 2:
                raise ValueError(f"invalid messages in {path}:{shard_rows}")
            if messages[0].get("role") != "user" or messages[1].get("role") != "assistant":
                raise ValueError(f"invalid roles in {path}:{shard_rows}")
            if not str(messages[0].get("content", "")).startswith("Ret OCR- og tekstfejlene.\\n\\n"):
                raise ValueError(f"invalid prompt in {path}:{shard_rows}")
            if repair.get("declared_ocr_edits") not in range(1, 9):
                raise ValueError(f"invalid edit receipt in {path}:{shard_rows}")
            shard_rows += 1
    if shard_rows != item["rows"]:
        raise ValueError(f"row count mismatch: {path}: {shard_rows} != {item['rows']}")
    rows += shard_rows
if rows != manifest["counts"]["kept"]:
    raise ValueError(f"package row count mismatch: {rows}")
print(json.dumps({"valid": True, "rows": rows, "dataset": manifest["name"]}))
'''


def final_readme(manifest: dict[str, Any]) -> str:
    return f'''---
license: cc-by-4.0
language:
- da
task_categories:
- text2text-generation
pretty_name: DFM11 Folketingets Dokumenter Error Correction
---

# DFM11 Folketingets Dokumenter Error Correction

This dataset is the fully audited DFM11 replacement for
`schneiderkamplab/dfm10-folketingets-dokumenter-error-correction`.

Every retained input was generated from its target using 1-8 declared
synthetic OCR substitutions. Deterministic text-quality filtering was followed
by a task-aware Gemma 4 audit of all {manifest["counts"]["seen"]:,} surviving
rows; {manifest["counts"]["rejected"]:,} audit rejections were removed and
{manifest["counts"]["kept"]:,} rows remain.

Rows contain `messages` in Gemma-compatible user/assistant form and provenance
and repair receipts under `metadata`.
'''


def finalize(args: argparse.Namespace) -> None:
    decisions: set[str] = set()
    rejected_by_file: dict[str, set[int]] = {}
    errors = 0
    rejected_reasons: Counter[str] = Counter()
    for path in args.audit:
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                if not line.strip():
                    continue
                verdict = json.loads(line)
                row_id = str(verdict["row_id"])
                if row_id in decisions:
                    raise ValueError(f"duplicate audit decision: {row_id}")
                decisions.add(row_id)
                if "error" in verdict:
                    errors += 1
                if not verdict.get("keep"):
                    filename, line_number = row_id.rsplit(":", 1)
                    rejected_by_file.setdefault(filename, set()).add(int(line_number))
                    rejected_reasons[str(verdict.get("primary_failure_type", "other"))] += 1
    if len(decisions) != args.expected_rows:
        raise ValueError(f"audit coverage {len(decisions)} != {args.expected_rows}")
    if errors:
        raise ValueError(f"full audit contains {errors} judge errors")

    sources = sorted((args.input / "data").glob("*.jsonl.gz"))
    if not sources:
        raise FileNotFoundError(args.input / "data")
    if args.output.exists():
        if not args.force:
            raise FileExistsError(args.output)
        shutil.rmtree(args.output)
    (args.output / "data").mkdir(parents=True)
    work = [
        (source, args.output / "data" / source.name, rejected_by_file.get(source.name, set()))
        for source in sources
    ]
    with ProcessPoolExecutor(max_workers=min(args.workers, len(work))) as pool:
        shard_counts = list(pool.map(_filter_audited_shard, work))
    totals: Counter[str] = Counter()
    for shard in shard_counts:
        totals.update({key: value for key, value in shard.items() if key in {"seen", "kept", "rejected"}})
    if totals["seen"] != args.expected_rows:
        raise ValueError(f"source rows {totals['seen']} != {args.expected_rows}")
    if totals["rejected"] != sum(map(len, rejected_by_file.values())):
        raise ValueError("not all rejected row IDs mapped to source shards")
    manifest = {
        "name": FINAL_PACKAGE_NAME,
        "intended_hf_id": FINAL_HF_ID,
        "upload_performed": False,
        "source_package": str(args.input),
        "source_repo": "schneiderkamplab/dfm10-folketingets-dokumenter-error-correction",
        "source_revision": SOURCE_REVISION,
        "license": "cc-by-4.0",
        "filter_contract": "folketing_error_correction_contract_v1_plus_full_task_aware_audit",
        "admission_status": "fully_audited",
        "counts": dict(totals),
        "data_files": [
            {
                "file": shard["file"],
                "rows": shard["kept"],
                "bytes": shard["bytes"],
                "sha256": shard["sha256"],
            }
            for shard in shard_counts
        ],
        "rejected_reasons": dict(rejected_reasons),
        "audit_files": [str(path) for path in args.audit],
    }
    atomic_write_json(args.output / "metadata" / "manifest.json", manifest)
    (args.output / "README.md").write_text(final_readme(manifest), encoding="utf-8")
    validator = args.output / "validate_dataset.py"
    validator.write_text(FINAL_VALIDATOR, encoding="utf-8")
    validator.chmod(0o755)
    print(json.dumps(manifest, indent=2, sort_keys=True))


def record_upload(args: argparse.Namespace) -> None:
    from huggingface_hub import HfApi, hf_hub_download

    token = os.environ.get(args.token_env)
    if not token:
        raise ValueError(f"missing Hugging Face token in ${args.token_env}")
    manifest_path = args.package / "metadata/manifest.json"
    manifest = json.loads(manifest_path.read_text())
    if manifest.get("intended_hf_id") != args.repo_id:
        raise ValueError("package intended_hf_id does not match upload repo")

    manifest["upload_performed"] = True
    atomic_write_json(manifest_path, manifest)
    api = HfApi(token=token)
    commit = api.upload_file(
        path_or_fileobj=str(manifest_path),
        path_in_repo="metadata/manifest.json",
        repo_id=args.repo_id,
        repo_type="dataset",
        commit_message="Record verified DFM11 Folketing audit package",
        token=token,
    )
    revision = api.dataset_info(args.repo_id, token=token).sha
    expected = {
        path.relative_to(args.package).as_posix()
        for path in args.package.rglob("*")
        if path.is_file() and ".cache" not in path.parts and "__pycache__" not in path.parts
    }
    remote = set(api.list_repo_files(args.repo_id, repo_type="dataset", revision=revision, token=token))
    missing = sorted(expected - remote)
    if missing:
        raise ValueError(f"remote upload is missing files: {missing[:10]}")
    downloaded_manifest = Path(
        hf_hub_download(
            args.repo_id,
            "metadata/manifest.json",
            repo_type="dataset",
            revision=revision,
            token=token,
        )
    )
    if downloaded_manifest.read_bytes() != manifest_path.read_bytes():
        raise ValueError("remote manifest differs from local manifest")

    config = args.config.read_text()
    if "revision: pending_full_audit_upload" not in config:
        if f"revision: {revision}" not in config:
            raise ValueError("DFM11 config has neither pending nor current upload revision")
    else:
        config = config.replace("revision: pending_full_audit_upload", f"revision: {revision}", 1)
    pending_rows = "available_rows: pending_full_audit"
    if pending_rows in config:
        config = config.replace(pending_rows, f"available_rows: {manifest['counts']['kept']}", 1)
    pending_status = "admission_status: full_task_aware_audit_in_progress"
    if pending_status in config:
        config = config.replace(pending_status, "admission_status: fully_audited", 1)
    temporary = args.config.with_name(f".{args.config.name}.tmp.{os.getpid()}")
    temporary.write_text(config, encoding="utf-8")
    os.replace(temporary, args.config)

    receipt = {
        "repo_id": args.repo_id,
        "revision": revision,
        "commit_url": str(commit.commit_url),
        "expected_files": len(expected),
        "missing": missing,
        "manifest_match": True,
        "rows": manifest["counts"]["kept"],
    }
    atomic_write_json(args.receipt, receipt)
    print(json.dumps(receipt, indent=2, sort_keys=True))


def gate(args: argparse.Namespace) -> None:
    decisions: dict[str, dict[str, Any]] = {}
    errors = 0
    for path in args.audit:
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                if not line.strip():
                    continue
                row = json.loads(line)
                decisions[str(row["row_id"])] = row
                errors += "error" in row
    kept = sum(row.get("keep") is True for row in decisions.values())
    keep_rate = kept / len(decisions) if decisions else 0.0
    failures = []
    if len(decisions) != args.expected_rows:
        failures.append(f"audited rows {len(decisions)} != {args.expected_rows}")
    if errors:
        failures.append(f"judge errors {errors} != 0")
    if keep_rate < args.minimum_keep_rate:
        failures.append(f"keep rate {keep_rate:.3%} < {args.minimum_keep_rate:.3%}")
    result = {
        "passed": not failures,
        "audited_rows": len(decisions),
        "kept_rows": kept,
        "keep_rate": keep_rate,
        "judge_errors": errors,
        "minimum_keep_rate": args.minimum_keep_rate,
        "audit_files": [str(path) for path in args.audit],
        "failures": failures,
    }
    atomic_write_json(args.output, result)
    print(json.dumps(result, indent=2, sort_keys=True))
    if failures:
        raise SystemExit(1)


def main() -> None:
    args = parse_args()
    {
        "build": build,
        "sample": sample,
        "audit": audit,
        "sidecar-unresolved": sidecar_unresolved,
        "finalize": finalize,
        "record-upload": record_upload,
        "gate": gate,
    }[args.command](args)


if __name__ == "__main__":
    main()
