"""Prepare transparent Baltic cards without inventing blanket source licenses."""
from collections import Counter
import json
from pathlib import Path
from dfm12.io import atomic,load,write_json,file_hash


def run(root):
    if not load(root/'complete.json')['success']:raise ValueError('Incomplete Baltic release')
    packages=[]
    for entry in load(root/'registry.json')['additions']:
        folder=Path(entry['output']).parent.parent
        sources=Counter();licenses=Counter()
        with Path(entry['output']).open() as stream:
            for line in stream:
                row=json.loads(line);origin=row.get('provenance',{}).get('source') or {}
                sources[str(origin.get('source',origin.get('repo','unidentified_source' if origin else 'synthetic_reference_or_scenario')))]+=1
                licenses[str(origin.get('license','not_declared_per_row'))]+=1
        language=entry['name'].split('_')[3]
        with atomic(folder/'README.md') as out:
            out.write('---\nlanguage: ['+language+']\ntask_categories: [text-generation]\nconfigs:\n'
                '- config_name: default\n  data_files:\n  - split: train\n    path: data/train.jsonl\n---\n\n'
                '# '+entry['name']+'\n\n'+str(entry['rows'])+' full conversations; '+str(entry['training_targets'])+
                ' assistant training targets. Preserve tools and all conversational history. '
                'Native Gemma rendering, thinking disabled; supervise each assistant target.\n\n'
                'Generated by Gemma 4 26B A4B and independently model-audited. Automated review is fallible, '
                'not native-speaker certification. Historical manual holds are excluded. '
                'Original source/reference provenance remains in each row. No blanket license is asserted. '
                'Source-specific rights and attribution must be retained; missing per-row license labels '
                'are not an unrestricted-use grant. See SOURCE_INVENTORY.json.\n')
        write_json(folder/'SOURCE_INVENTORY.json',dict(sources=dict(sources),license_labels=dict(licenses),
            data_sha256=entry['output_sha256'],rights_review_required='not_declared_per_row' in licenses,
            source_terms_not_relicensed=True))
        family=entry['name'].split('_',4)[4].replace('_','-')
        ready=set(sources)=={'synthetic_reference_or_scenario'} and family in ('math-code','tool-dialogue')
        packages.append(dict(name=entry['name'],rows=entry['rows'],training_targets=entry['training_targets'],
            hf_repo_id=f'schneiderkamplab/dfm13-multilingual-{family}-{language}',
            metadata_prepared=True,uploaded=False,upload_ready=ready,
            remaining='HF publication and remote verification' if ready else 'Bind source-specific publication rights/attribution; no blanket licensing',
            readme_sha256=file_hash(folder/'README.md')))
    write_json(root/'upload-readiness.json',dict(packages=packages,uploaded=False))


if __name__=='__main__':run(Path('data/dfm13/baltic-finished-release-20261004-v1'))
